#!/usr/bin/env python3
"""
Auto-generated custom hypothesis test script.

Description: Test if cases with longer PFT#10 root turnover times achieve higher fine root biomass, and whether root distribution parameters correlate with P limitation severity
Hypothesis: Arctic Graminoid Root Persistence Hypothesis
Generated: 2026-02-12T00:41:29.509550

This script was generated by Claude AI to test a specific hypothesis
using existing Morris ensemble data.
"""

import numpy as np
try:
    from scipy import stats
except ImportError:
    stats = None

# Custom test function from Claude
def test_hypothesis(param_matrix, y_outputs, screening_data, config):
    import numpy as np
    from scipy import stats
    
    # Build PFT column mapping
    pft_ids = config.get('pft_ids', [7, 9, 10])
    PFT_COL = {pft: i for i, pft in enumerate(pft_ids)}
    param_names = config['param_names']
    
    def _safe_index(names, name):
        try:
            return names.index(name)
        except ValueError:
            return None
    
    # Get turnover parameter for PFT#10
    idx_turn = _safe_index(param_names, 'turnover_fnrt_10')
    idx_prof_a = _safe_index(param_names, 'fnrt_prof_a_10')
    idx_prof_b = _safe_index(param_names, 'fnrt_prof_b_10')
    
    if idx_turn is None:
        return {'supported': False, 'confidence': 0.0,
                'evidence': {'error': 'turnover_fnrt_10 not found'}, 'insights': []}
    
    turnover_vals = param_matrix[:, idx_turn]
    
    # Get fine root biomass
    froot = y_outputs.get('froot_biomass')
    if froot is None:
        return {'supported': False, 'confidence': 0.0,
                'evidence': {'error': 'froot_biomass not in y_outputs'}, 'insights': []}
    
    froot_pft10 = froot[:, PFT_COL[10]]
    
    # Test 1: Correlation between turnover time and froot biomass
    corr_turn, p_turn = stats.pearsonr(turnover_vals, froot_pft10)
    
    # Test 2: Compare high vs low turnover cases
    high_turn = turnover_vals > 3.0
    low_turn = turnover_vals < 2.0
    
    if np.sum(high_turn) > 5 and np.sum(low_turn) > 5:
        froot_high = np.mean(froot_pft10[high_turn])
        froot_low = np.mean(froot_pft10[low_turn])
        improvement_factor = froot_high / max(froot_low, 1e-6)
    else:
        improvement_factor = np.nan
    
    # Test 3: Root distribution impact (if available)
    evidence = {
        'turnover_correlation': float(corr_turn),
        'turnover_p_value': float(p_turn),
        'high_turnover_mean_froot': float(froot_high) if not np.isnan(improvement_factor) else None,
        'low_turnover_mean_froot': float(froot_low) if not np.isnan(improvement_factor) else None,
        'improvement_factor': float(improvement_factor) if not np.isnan(improvement_factor) else None
    }
    
    insights = [
        f'Turnover-froot correlation: r={corr_turn:.3f}, p={p_turn:.3f}',
        f'High turnover (>3yr) cases have {improvement_factor:.1f}x more froot' if not np.isnan(improvement_factor) else 'Insufficient turnover variation'
    ]
    
    # Add root distribution analysis if parameters available
    if idx_prof_a is not None and idx_prof_b is not None:
        prof_a_vals = param_matrix[:, idx_prof_a]
        prof_b_vals = param_matrix[:, idx_prof_b]
        
        # Lower a and b = deeper roots
        root_depth_score = -(prof_a_vals + prof_b_vals)  # Negative so higher = deeper
        corr_depth, p_depth = stats.pearsonr(root_depth_score, froot_pft10)
        
        evidence['root_depth_correlation'] = float(corr_depth)
        evidence['root_depth_p_value'] = float(p_depth)
        insights.append(f'Deeper roots correlate with froot: r={corr_depth:.3f}')
    
    # Supported if turnover strongly correlates and/or high turnover shows improvement
    supported = (corr_turn > 0.3 and p_turn < 0.05) or (improvement_factor > 2.0 if not np.isnan(improvement_factor) else False)
    confidence = min(0.9, abs(corr_turn) * 1.5) if supported else 0.3
    
    return {
        'supported': supported,
        'confidence': confidence,
        'evidence': evidence,
        'insights': insights
    }
