#!/usr/bin/env python3
"""
Auto-generated custom hypothesis test script.

Description: Analyze which parameters are at bounds and their impact on target failures
Hypothesis: Phase 0 Morris Bounds Redesign for P-Limited System
Generated: 2026-02-12T00:50:04.963389

This script was generated by Claude AI to test a specific hypothesis
using existing Morris ensemble data.
"""

import numpy as np
try:
    from scipy import stats
except ImportError:
    stats = None

# Custom test function from Claude
def test_hypothesis(param_matrix, y_outputs, screening_data, config):
    import numpy as np
    
    # Build PFT column mapping
    pft_ids = config.get('pft_ids', [7, 9, 10])
    PFT_COL = {pft: i for i, pft in enumerate(pft_ids)}
    param_names = config['param_names']
    
    # Known bounds for key parameters (from ensemble list)
    param_bounds = {
        'vmax_ptase_7': [5e-10, 0.0005],
        'vmax_ptase_9': [5e-10, 0.0005],
        'vmax_ptase_10': [5e-10, 0.0005],
        'vmax_p_7': [5e-11, 0.00005],
        'vmax_p_9': [5e-11, 0.00005],
        'vmax_p_10': [5e-11, 0.00005],
        'l2fr_ini_7': [0.01, 2.956620991],
        'l2fr_ini_9': [0.01, 18.31149756],
        'l2fr_ini_10': [1.115169823, 9.879038859]
    }

    # This promoted test hardcodes api-31 SHORTHAND names (PFTs 7/9/10). Under the docs/37
    # canonical-id scheme (or a different api epoch) none match `param_names`; rather than
    # silently reporting "0 at bounds" (docs/37 §5 #2), flag that the hardcoded set is stale.
    if not any(p in param_names for p in param_bounds):
        return {
            'supported': False,
            'confidence': 0.0,
            'evidence': {'params_at_bounds': 0,
                         'note': 'hardcoded api-31 shorthand param set (vmax_p_7, l2fr_ini_10, ...) is '
                                 'not present in the current ensemble param_names — likely a different '
                                 'api epoch / the docs/37 canonical-id scheme. Regenerate this test.'},
            'insights': ['NOT APPLICABLE: this promoted test uses api-31 shorthand names that do not '
                         'match the current ensemble param_names.'],
        }

    # Check which parameters are at bounds
    at_bounds = {}
    bound_impact = {}
    
    for param, bounds in param_bounds.items():
        idx = param_names.index(param) if param in param_names else None
        if idx is not None:
            values = param_matrix[:, idx]
            at_lower = np.sum(np.abs(values - bounds[0]) < 1e-10)
            at_upper = np.sum(np.abs(values - bounds[1]) < 1e-10)
            total_at_bounds = at_lower + at_upper
            
            if total_at_bounds > 0:
                at_bounds[param] = {
                    'lower': at_lower,
                    'upper': at_upper,
                    'fraction': total_at_bounds / len(values)
                }
                
                # Check correlation with target failures
                froot = y_outputs.get('froot_biomass', np.zeros_like(values))
                if param.endswith('_10') and froot.shape[1] > PFT_COL[10]:
                    froot_pft10 = froot[:, PFT_COL[10]]
                    cases_at_bounds = (np.abs(values - bounds[0]) < 1e-10) | (np.abs(values - bounds[1]) < 1e-10)
                    mean_at_bounds = np.mean(froot_pft10[cases_at_bounds]) if np.any(cases_at_bounds) else 0
                    mean_interior = np.mean(froot_pft10[~cases_at_bounds]) if np.any(~cases_at_bounds) else 0
                    bound_impact[param] = mean_at_bounds - mean_interior
    
    # Analyze impact
    n_params_at_bounds = len(at_bounds)
    total_params = len(param_bounds)
    fraction_at_bounds = n_params_at_bounds / total_params if total_params > 0 else 0
    
    # Check P-uptake parameters specifically
    p_params_at_bounds = [p for p in at_bounds if 'vmax_p' in p or 'vmax_ptase' in p]
    
    insights = [
        f"{n_params_at_bounds}/{total_params} key parameters at bounds ({fraction_at_bounds:.1%})",
        f"P-uptake parameters at bounds: {len(p_params_at_bounds)}",
        f"Most constrained: {max(at_bounds.items(), key=lambda x: x[1]['fraction'])[0] if at_bounds else 'none'}"
    ]
    
    # Evidence that bounds prevent finding solutions
    evidence = {
        'params_at_bounds': n_params_at_bounds,
        'fraction_at_bounds': float(fraction_at_bounds),
        'p_params_constrained': len(p_params_at_bounds),
        'bound_impacts': {k: float(v) for k, v in bound_impact.items()}
    }
    
    # Support hypothesis if >25% parameters at bounds and P-parameters constrained
    supported = fraction_at_bounds > 0.25 and len(p_params_at_bounds) > 2
    
    return {
        'supported': supported,
        'confidence': min(0.95, fraction_at_bounds + 0.3),
        'evidence': evidence,
        'insights': insights
    }
