"""
FATES Output Variable Parser for A2MC

Parses ELM-FATES output variable definitions from CDL files
(generated by ncdump -h). Extracts variable metadata including
dimensions, units, long_name, and cell_methods.

This is the output-side counterpart to parameter_parser.py.

Author: Jing Tao with Claude
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


# =============================================================================
# Key ELM variables to include (beyond FATES_* prefix)
# =============================================================================

KEY_ELM_VARIABLES = [
    "LABILEP", "SECONDP", "OCCLP", "LABILEP_vr", "SECONDP_vr",
    "SMIN_NH4", "SMIN_NO3", "SMIN_NH4_vr", "SMIN_NO3_vr",
    "ACTUAL_IMMOB", "ACTUAL_IMMOB_P", "DENIT",
    "HR", "NEE", "NEP", "GPP",
    "TOTSOMC", "TOTLITC", "TOTLITN", "TOTLITP",
    "BIOCHEM_PMIN", "BIOCHEM_PMIN_TO_PLANT",
    "BTRAN", "QFLX_EVAP_TOT",
]

# =============================================================================
# Dimension level mapping
# =============================================================================

DIMENSION_LEVEL_MAP = {
    "fates_levpft": "pft",
    "fates_levscpf": "szpf",
    "fates_levscls": "size_class",
    "fates_levage": "age",
    "fates_levelem": "element",
    "fates_levcan": "canopy",
    "fates_levscag": "size_age",
    "fates_levscagpf": "size_age_pft",
    "fates_levcapf": "cohort_age_pft",
    "fates_levheight": "height",
    "fates_levfuel": "fuel",
    "fates_levcwdsc": "cwd_size",
    "fates_levleaf": "leaf",
    "fates_levcnlf": "canopy_leaf",
    "fates_levcnlfpf": "canopy_leaf_pft",
    "fates_levcdsc": "damage_size",
    "fates_levcdpf": "damage_pft",
    "fates_levcdam": "damage",
    "fates_levagepft": "age_pft",
    "fates_levelpft": "element_pft",
    "fates_levelcwd": "element_cwd",
    "fates_levelage": "element_age",
    "fates_levagefuel": "age_fuel",
    "levdcmp": "decomp_layer",
    "levgrnd": "ground_layer",
    "levsoi": "soil_layer",
}

# =============================================================================
# Output variable category inference from name
# =============================================================================

OUTPUT_CATEGORIES = {
    # FATES variable name patterns -> category
    "GPP": "carbon_flux",
    "NPP": "carbon_flux",
    "AR": "carbon_flux",
    "AUTORESP": "carbon_flux",
    "GROWTH_RESP": "carbon_flux",
    "MAINT_RESP": "carbon_flux",
    "EXCESS_RESP": "carbon_flux",
    "DEMOTION": "carbon_flux",
    "PROMOTION": "carbon_flux",
    "LEAFC": "biomass",
    "FROOTC": "biomass",
    "STOREC": "biomass",
    "SAPWOODC": "biomass",
    "STRUCTC": "biomass",
    "VEGC": "biomass",
    "REPROC": "biomass",
    "DEADWOODC": "biomass",
    "CROOT": "biomass",
    "ALLOC": "allocation",
    "L2FR": "allocation",
    "SEED": "seed",
    "RECRUIT": "recruitment",
    "NPLANT": "demography",
    "NESTEROV": "fire",
    "FIRE": "fire",
    "BURN": "fire",
    "FDI": "fire",
    "MORT": "mortality",
    "CARBON_STARV": "mortality",
    "PHEN": "phenology",
    "COLD_STATUS": "phenology",
    "DROUGHT_STATUS": "phenology",
    "GDD": "phenology",
    "DAYSINCE": "phenology",
    "ELONG_FACTOR": "phenology",
    "LAI": "canopy",
    "CROWN": "canopy",
    "CANOPY": "canopy",
    "SPREAD": "canopy",
    "PUPTAKE": "nutrient",
    "NUPTAKE": "nutrient",
    "NH4UPTAKE": "nutrient",
    "NO3UPTAKE": "nutrient",
    "NDEMAND": "nutrient",
    "PDEMAND": "nutrient",
    "NEFFLUX": "nutrient",
    "PEFFLUX": "nutrient",
    "LITTER": "litter",
    "CWD": "litter",
    "FRAG": "litter",
    "TURNOVER": "turnover",
    "DISTURBANCE": "disturbance",
    "PATCH": "patch",
    "AREA_PLANTS": "demography",
    "AREA_TREES": "demography",
    "BASAL": "demography",
    "DDBH": "growth",
    "HEIGHT": "structure",
    "TRIMMING": "canopy",
    "STOMATAL": "physiology",
    "HYDR": "hydraulics",
    "BTRAN": "hydraulics",
    "SCORCH": "fire",
    "ERROR": "diagnostics",
    "CBALANCE": "diagnostics",
    # ELM-level categories
    "HR": "carbon_flux",
    "NEE": "carbon_flux",
    "NEP": "carbon_flux",
    "TOTSOMC": "soil_carbon",
    "TOTLITC": "litter",
    "TOTLITN": "litter",
    "TOTLITP": "litter",
    "LABILEP": "soil_nutrient",
    "SECONDP": "soil_nutrient",
    "OCCLP": "soil_nutrient",
    "SMIN_NH4": "soil_nutrient",
    "SMIN_NO3": "soil_nutrient",
    "ACTUAL_IMMOB": "nutrient",
    "DENIT": "nutrient",
    "BIOCHEM_PMIN": "soil_nutrient",
    "QFLX": "water_flux",
}


@dataclass
class FATESOutputVariable:
    """Represents a single ELM-FATES output variable with metadata."""

    name: str
    dimensions: List[str] = field(default_factory=list)
    units: str = ""
    long_name: str = ""
    data_type: str = "float"
    cell_methods: str = ""

    @property
    def is_fates(self) -> bool:
        """True if name starts with FATES_."""
        return self.name.startswith("FATES_")

    @property
    def dimension_level(self) -> str:
        """Determine aggregation level: site, pft, szpf, etc."""
        # Check each dimension against the mapping
        for dim in self.dimensions:
            if dim in DIMENSION_LEVEL_MAP:
                return DIMENSION_LEVEL_MAP[dim]
        # If only time and lndgrid/gridcell, it's site-level
        non_standard = [d for d in self.dimensions
                        if d not in ("time", "lndgrid", "gridcell")]
        if not non_standard:
            return "site"
        return "other"

    @property
    def category(self) -> str:
        """Infer category from variable name patterns."""
        # Strip FATES_ prefix for matching
        search_name = self.name
        if search_name.startswith("FATES_"):
            search_name = search_name[6:]

        # Try longest match first (more specific patterns)
        for pattern in sorted(OUTPUT_CATEGORIES.keys(), key=len, reverse=True):
            if pattern in search_name:
                return OUTPUT_CATEGORIES[pattern]

        return "other"

    def __repr__(self) -> str:
        dims = f"({', '.join(self.dimensions)})" if self.dimensions else "(scalar)"
        return f"FATESOutputVariable({self.name}{dims})"


class FATESOutputParser:
    """
    Parse ELM-FATES output variable definitions from CDL files.

    CDL files are generated by `ncdump -h output.nc`.

    Parameters
    ----------
    file_path : str
        Path to CDL file containing output variable definitions
    """

    def __init__(self, file_path: str):
        self.file_path = Path(file_path)
        if not self.file_path.exists():
            raise FileNotFoundError(f"Output CDL file not found: {file_path}")
        self._variables: Optional[Dict[str, FATESOutputVariable]] = None
        self._dimensions: Optional[Dict[str, int]] = None

    def parse(self) -> Dict[str, FATESOutputVariable]:
        """Parse all output variables from CDL file.

        Returns
        -------
        Dict[str, FATESOutputVariable]
            Dictionary mapping variable names to FATESOutputVariable objects
        """
        if self._variables is not None:
            return self._variables

        content = self.file_path.read_text()

        # Parse dimensions
        self._dimensions = self._parse_dimensions(content)

        # Parse variables
        self._variables = {}

        # Match variable declarations: type NAME(dim1=size1, dim2=size2, ...);
        # Output CDL uses inline dimension sizes: float FATES_GPP(time=12, lndgrid=1);
        var_pattern = re.compile(
            r'^\s+(float|double|int)\s+(\w+)\(([^)]+)\)\s*;',
            re.MULTILINE
        )

        for match in var_pattern.finditer(content):
            data_type = match.group(1)
            name = match.group(2)
            dims_str = match.group(3)

            # Extract dimension names (strip =size)
            dims = [d.split("=")[0].strip() for d in dims_str.split(",")]

            self._variables[name] = FATESOutputVariable(
                name=name,
                dimensions=dims,
                data_type=data_type,
            )

        # Parse attributes (long_name, units, cell_methods)
        self._parse_attributes(content)

        return self._variables

    def _parse_dimensions(self, content: str) -> Dict[str, int]:
        """Parse dimension declarations from CDL content."""
        dimensions = {}
        dim_section = re.search(
            r'dimensions:\s*\n(.*?)(?=variables:|data:|$)',
            content, re.DOTALL
        )
        if dim_section:
            for match in re.finditer(r'(\w+)\s*=\s*(\d+|UNLIMITED)', dim_section.group(1)):
                dim_name = match.group(1)
                dim_value = match.group(2)
                if dim_value == "UNLIMITED":
                    dimensions[dim_name] = -1  # Marker for unlimited
                else:
                    dimensions[dim_name] = int(dim_value)
        return dimensions

    def _parse_attributes(self, content: str):
        """Parse variable attributes (units, long_name, cell_methods)."""
        # CDL output format uses indented attributes under variable declarations:
        #   float FATES_GPP(time=12, lndgrid=1);
        #     :long_name = "gross primary production";
        #     :units = "kg m-2 s-1";
        #     :cell_methods = "time: mean";

        current_var = None
        var_decl_pattern = re.compile(
            r'^\s+(?:float|double|int)\s+(\w+)\('
        )
        attr_pattern = re.compile(
            r'^\s+:(\w+)\s*=\s*"([^"]*)"'
        )

        for line in content.splitlines():
            # Check for variable declaration
            m = var_decl_pattern.match(line)
            if m:
                current_var = m.group(1)
                continue

            # Check for attribute under current variable
            m = attr_pattern.match(line)
            if m and current_var and current_var in self._variables:
                attr_name = m.group(1)
                attr_value = m.group(2)
                var = self._variables[current_var]
                if attr_name == "units":
                    var.units = attr_value
                elif attr_name == "long_name":
                    var.long_name = attr_value
                elif attr_name == "cell_methods":
                    var.cell_methods = attr_value

            # Non-attribute, non-empty lines reset current_var
            elif line.strip() and not line.strip().startswith(":") and not line.strip().startswith("//"):
                current_var = None

    def get_dimensions(self) -> Dict[str, int]:
        """Get dimension names and sizes."""
        if self._dimensions is None:
            self.parse()
        return self._dimensions

    def get_fates_variables(self) -> Dict[str, FATESOutputVariable]:
        """Get only FATES_* variables."""
        variables = self.parse()
        return {k: v for k, v in variables.items() if v.is_fates}

    def get_elm_variables(self) -> Dict[str, FATESOutputVariable]:
        """Get only non-FATES (ELM-level) variables."""
        variables = self.parse()
        return {k: v for k, v in variables.items() if not v.is_fates}

    def get_key_elm_variables(self) -> Dict[str, FATESOutputVariable]:
        """Get the subset of ELM variables relevant for calibration."""
        variables = self.parse()
        result = {}
        for name in KEY_ELM_VARIABLES:
            if name in variables:
                result[name] = variables[name]
            # Also look for _vr variants
            vr_name = f"{name}_vr"
            if vr_name in variables:
                result[vr_name] = variables[vr_name]
        return result

    def get_variables_by_dimension(self) -> Dict[str, List[FATESOutputVariable]]:
        """Group variables by their dimension level."""
        variables = self.parse()
        by_dim = {}
        for var in variables.values():
            level = var.dimension_level
            if level not in by_dim:
                by_dim[level] = []
            by_dim[level].append(var)
        return by_dim

    def get_variables_by_category(self) -> Dict[str, List[FATESOutputVariable]]:
        """Group variables by inferred category."""
        variables = self.parse()
        by_cat = {}
        for var in variables.values():
            cat = var.category
            if cat not in by_cat:
                by_cat[cat] = []
            by_cat[cat].append(var)
        return by_cat


# =============================================================================
# Main (for testing)
# =============================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python output_parser.py <output_cdl_file>")
        sys.exit(1)

    file_path = sys.argv[1]
    parser = FATESOutputParser(file_path)
    variables = parser.parse()
    dims = parser.get_dimensions()

    print(f"\nParsed {len(variables)} total output variables from {file_path}")

    fates_vars = parser.get_fates_variables()
    elm_vars = parser.get_elm_variables()
    key_elm = parser.get_key_elm_variables()
    print(f"  FATES variables: {len(fates_vars)}")
    print(f"  ELM variables: {len(elm_vars)}")
    print(f"  Key ELM variables found: {len(key_elm)}")

    print(f"\nDimensions:")
    for name, size in sorted(dims.items()):
        print(f"  {name}: {size}")

    print(f"\nVariables by dimension level:")
    by_dim = parser.get_variables_by_dimension()
    for level, vars_list in sorted(by_dim.items()):
        print(f"  {level}: {len(vars_list)} variables")

    print(f"\nVariables by category:")
    by_cat = parser.get_variables_by_category()
    for cat, vars_list in sorted(by_cat.items()):
        print(f"  {cat}: {len(vars_list)} variables")

    print(f"\nSample FATES variables (first 10):")
    for i, (name, var) in enumerate(sorted(fates_vars.items())[:10]):
        print(f"  {var.name} [{var.units}] ({var.dimension_level}) - {var.long_name[:60]}")

    print(f"\nKey ELM variables:")
    for name, var in sorted(key_elm.items()):
        print(f"  {var.name} [{var.units}] ({var.dimension_level}) - {var.long_name[:60]}")
